### ISSUE TITLE
タスク：DBとcakephpのフレームワークの構築

### ISSUE THREAD

**Issue by kikutou** [kikutou/chokohon#10]
詳細設計書を見て、DBの構築とフレームワークの構築を着手してください。
完了したら、みなさんと一緒にレビューして、
問題がなければ、githubにpushしてください。

**Comment by kikutou** [comment]
@@DBの構築が完了したら、DBのエクスポートファイルをこちらにアップロードしてください。

**Comment by Caizhan777** [comment]
[Dump20170907.txt](https://github.com/kikutou/chokohon/files/1283433/Dump20170907.txt)

**Comment by Caizhan777** [comment]
DBのエクスポートファイルをアップロードしました、ご確認お願いします
[Dump20170907.txt](https://github.com/kikutou/chokohon/files/1283434/Dump20170907.txt)

**Comment by Caizhan777** [comment]
@kikutou DBとフレームワークはもうgitbubにpusｈしました、ご確認お願いします。

**Comment by kikutou** [comment]
確認しました。
クローズいたします。
