### ISSUE TITLE
バグ: フリルのＤＢ設計

### ISSUE THREAD

**Issue by akira0831** [kikutou/chokohon#12]
販売状況という検索条件が存在しないため、
「販売状況」を削除させていただけました！
新しく設計されたＤＢ設計は以下の通りです。

フリル検索情報テーブル・fril_rules（ヤオ）

・ID　id int pk/autoIncreament
・図書ID　book_id int fk(books.id)
・キーワード　key_words longtext
・カテゴリID　category_id int
・商品状態 book_status int
・発送状況　delivery_id int
### **・販売状況 sale_status int(廃棄となりました)**
・作成時間　created datetime default:now
・更新時間　updated datetime
・削除フラグ　del_flg　smallint default:0

**Comment by kikutou** [comment]
了解です。
wikiに直接DB設計書を修正してください。
修正が終わったら、サイに通知してください。

**Comment by Caizhan777** [comment]
分かりました、今からDBの構築を修正します

**Comment by akira0831** [comment]
バグ: フリルのＤＢ設計の内容を修正してもらいました。ご報告いたします。

**Comment by kikutou** [comment]
確認しました。
クローズします。
