### ISSUE TITLE
タスク：ラクマの各検索条件のIDの調査

### ISSUE THREAD

**Issue by akira0831** [kikutou/chokohon#13]
ラクマ上に、各条件に対応するIDに関しての調査が完了しました。
ご確認の程、よろしくお願いいたします。
Wikiへのリンク
https://github.com/kikutou/chokohon/wiki/%E3%82%BF%E3%82%B9%E3%82%AF%EF%BC%9A%E3%83%A9%E3%82%AF%E3%83%9E%E3%81%AE%E5%90%84%E6%A4%9C%E7%B4%A2%E6%9D%A1%E4%BB%B6%E3%81%AEID%E3%81%AE%E8%AA%BF%E6%9F%BB

**Comment by kikutou** [comment]
確認しました。
問題ありません。
