### ISSUE TITLE
タスク：ｐｈｐのHTML解析のソースの導入

### ISSUE THREAD

**Issue by kikutou** [kikutou/chokohon#16]
PHPのHTML解析のライブラリをcakephpのライブラリファイルとして導入してください。

**Comment by whb1324** [comment]
HTML解析のライブラリをCakephpの中に導入する方法：
1.プロジェクトのフォルダを開けて、composer.jsonファイルの
"require": {
      ......
    },
中に"shark/simple_html_dom":"dev-master"を追加する;
2.プロジェクトフォルダ配下に、端末を開けて、composer update shark/simple_html_domというコマンドを実行する。
3.vendor/shark/simple_html_dom/shimple_html_dom.phpファイル中に、
if (!defined('MAX_FILE_SIZE')) {
    define('MAX_FILE_SIZE', 600000);	
}
「600000」を「6000000」に直してください。

**Comment by whb1324** [comment]
cakephpHTML解析モジュールにて、"call a undefined function file_get_html()"というエラーメッセージが出力されました。理由としては、simple_html_dom.phpを導入しなかったのが主な原因だと思います。composerを利用して、上記の問題を簡単に解決できます。

**Comment by kikutou** [comment]
問題なし、クローズします。
