### ISSUE TITLE
タスク：フリルのDB設計

### ISSUE THREAD

**Issue by kikutou** [kikutou/chokohon#2]
以下のwikiを参照して、フリルの検索条件用のDBを設計してください。
完了したら、直接wikiを更新してください。
https://github.com/kikutou/chokohon/wiki/DB%E8%A8%AD%E8%A8%88

**Comment by akira0831** [comment]
フリルのテーブル名が変更になりました、ご報告いたします。

**Comment by kikutou** [comment]
チェックしました。問題ありません。「
