### ISSUE TITLE
タスク：ラクマのDB設計

### ISSUE THREAD

**Issue by kikutou** [kikutou/chokohon#3]
以下のwikiを参照して、ラクマのDBを設計してください。
完了したら、直接wikiに更新してください。
https://github.com/kikutou/chokohon/wiki/DB%E8%A8%AD%E8%A8%88

**Comment by zzzack** [comment]
出来上がりました、チェックしていただけませか。

**Comment by akira0831** [comment]
フリルのテーブル名が変更になりました、ご報告いたします。

**Comment by kikutou** [comment]
ヤオにチェックしてください。

**Comment by akira0831** [comment]
ラクマのDB設計を確認しました。
フリルの検索条件とほぼ同じ仕組みになっていますので、問題は特にありません。
以上です。

**Comment by kikutou** [comment]
了解です。クローズします。
