### ISSUE TITLE
バグ：DBの設計

### ISSUE THREAD

**Issue by kikutou** [kikutou/chokohon#4]
下記のwikiのDB設計書に各テーブルに対して、del_flg　smallint default:0　のフィールを追加してください。
完了したら、直接wikiを更新してください。
https://github.com/kikutou/chokohon/wiki/DB%E8%A8%AD%E8%A8%88/_edit

**Comment by Caizhan777** [comment]
完了しました。
ご確認お願いします。

**Comment by kikutou** [comment]
確認しました。問題ありません。
