### ISSUE TITLE
調査：AmazonのAPI

### ISSUE THREAD

**Issue by kikutou** [kikutou/chokohon#5]
AmazonのAPIを経由して、
商品のISNコードと名前を提供して、該当商品の中古販売状況を取得するAPIが有るかどう日を調査してくだい。
例として、下記のAPIドキュメントを参照してください。
https://images-na.ssl-images-amazon.com/images/G/09/associates/paapi/dg/index.html

調査が完了したら、
wikiのアーキテクチャ設計（２）も合わせて修正してください。
https://github.com/kikutou/chokohon/wiki/%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83%A3%E8%A8%AD%E8%A8%88%282%29

**Comment by lintongcai** [comment]
Marketplace Web Service Productsというフォイルをダウンロードしました。
インターフェイスみたい感じ。
 * SellerId: string
 * MWSAuthToken: string
 * MarketplaceId: string
 * Query: string
 * QueryContextId: string

バラメータが必要です。
とうやって実行まだ分かりません。

**Comment by kikutou** [comment]
APIのドキュメントのリンクがあれば、提供してください。

**Comment by lintongcai** [comment]
ダウンロードのリンク以下です。ご覧ください。
https://images-cn.ssl-images-amazon.com/images/G/01/mwsportal/clientlib/Products/2011-10-01/MWSProductsPHPClientLibrary-2011-10-01._V531003271_.zip
　　
亚马逊APIの商品検査について、リンク以下です。　　
[http://docs.developer.amazonservices.com/zh_CN/products/Products_ListMatchingProducts.html](http://docs.developer.amazonservices.com/zh_CN/products/Products_ListMatchingProducts.html)

**Comment by kikutou** [comment]
wikiに書いたとおり、APIの利用は廃棄します。
