### ISSUE TITLE
調査：PHPのHTML解析モジュール

### ISSUE THREAD

**Issue by kikutou** [kikutou/chokohon#6]
PHPのHTML解析用のモジュールを調査して、
今回の条件に合うかつ利用しやすいモジュールを提案してください。

調査が出たら、下記のwikiを修正してください。
https://github.com/kikutou/chokohon/wiki/%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83%A3%E8%A8%AD%E8%A8%88%282%29

**Comment by whb1324** [comment]
更新しました。
確認してください。

**Comment by kikutou** [comment]
使い方のドキュメントがあれば、提供してください。

**Comment by whb1324** [comment]
ドキュメントのサイトを更新しました。
確認してください。

**Comment by kikutou** [comment]
確認しました。問題ありません。クローズします。
