### ISSUE TITLE
タスク：フリルのモデルの詳細設計

### ISSUE THREAD

**Issue by kikutou** [kikutou/chokohon#7]
フリルの詳細設計を
メルカリ部分を参照して、再生してください。
https://github.com/kikutou/chokohon/wiki/%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83%A3%E8%A8%AD%E8%A8%88%282%29

**Comment by akira0831** [comment]
モデル内容が変更になしましたので、ご報告いたします。　変更内容：フリルモデルの追加です。

**Comment by kikutou** [comment]
確認しました。問題ありません。
