### ISSUE TITLE
タスク：フリルの各検索条件のIDの調査

### ISSUE THREAD

**Issue by kikutou** [kikutou/chokohon#9]
フリル上に、各条件に対応するIDを調査してください。
調査が完了したら、wikiに記録してください。

例えば、
・カテゴリID　category_id int
フリル上には、今回対応しているコラムは以下になる。
エンタメ・ホビー/本/すべて　733
....

**Comment by akira0831** [comment]
検索条件に応じて各idの指定内容は以下となります。
ご確認のほど、よろしくお願いします。

・カテゴリID　category_id int
エンタメ・ホビー/本/すべて　733
エンタメ・ホビー/本/文学/小説　734
エンタメ・ホビー/本/人文/社会　735
エンタメ・ホビー/本/ノンフィクション/教養　736
エンタメ・ホビー/本/地図/旅行ガイド　737
エンタメ・ホビー/本/ビジネス/経済　738
エンタメ・ホビー/本/健康/医学　739
エンタメ・ホビー/本/コンピュータ/IT　740
エンタメ・ホビー/本/趣味/スポーツ/実用　741
エンタメ・ホビー/本/住まい/暮らし/子育て　742
エンタメ・ホビー/本/アート/エンタメ 　743
エンタメ・ホビー/本/洋書 　744
エンタメ・ホビー/本/その他 　745
エンタメ・ホビー/本/絵本/児童書 　1663
エンタメ・ホビー/本/参考書 　1664
エンタメ・ホビー/本/資格/検定 　1665

**Comment by akira0831** [comment]
フリル上に、各条件に対応するIDに関して、調査が完了しました。
調査内容がＷikiに書いてあります。
ご確認の程、よろしくお願いいたします。
https://github.com/kikutou/chokohon/wiki/%E3%82%BF%E3%82%B9%E3%82%AF%EF%BC%9A%E3%83%95%E3%83%AA%E3%83%AB%E3%81%AE%E5%90%84%E6%A4%9C%E7%B4%A2%E6%9D%A1%E4%BB%B6%E3%81%AEID%E3%81%AE%E8%AA%BF%E6%9F%BB

**Comment by kikutou** [comment]
確認しました。
問題ありません。
